import type { RouteRecordRaw } from 'vue-router'

export const administrationRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/login',
    name: 'admin.login',
    component: () => import('./pages/AdminLoginPage.vue'),
    meta: { layout: 'blank' },
  },
  {
    path: '/admin',
    name: 'admin.dashboard',
    component: () => import('./pages/AdminDashboardPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/orders',
    name: 'admin.orders',
    component: () => import('./pages/AdminOrdersPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/calendar',
    name: 'admin.calendar',
    component: () => import('./pages/AdminCalendarPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/products',
    name: 'admin.products',
    component: () => import('./pages/AdminProductsPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/productos/new',
    name: 'admin.products.create',
    component: () => import('./pages/AdminProductFormPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/productos/:id',
    name: 'admin.products.edit',
    component: () => import('./pages/AdminProductFormPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/options',
    name: 'admin.options',
    component: () => import('./pages/AdminOptionsPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/categories',
    name: 'admin.categories',
    component: () => import('./pages/AdminCategoriesPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/cms',
    name: 'admin.cms',
    component: () => import('./pages/AdminCmsPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/menus',
    name: 'admin.menus',
    component: () => import('./pages/AdminMenusPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/theme',
    name: 'admin.theme',
    component: () => import('./pages/AdminThemePage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/payments',
    name: 'admin.payments',
    component: () => import('./pages/AdminPaymentsPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/emails',
    name: 'admin.emails',
    component: () => import('./pages/AdminEmailsPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/notifications',
    name: 'admin.notifications',
    component: () => import('./pages/AdminNotificationsPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/users',
    name: 'admin.users',
    component: () => import('./pages/UsersPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/roles',
    name: 'admin.roles',
    component: () => import('./pages/RolesPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/audit',
    name: 'admin.audit',
    component: () => import('./pages/AuditLogPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/security',
    name: 'admin.security',
    component: () => import('./pages/SecurityPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/profile',
    name: 'admin.profile',
    component: () => import('./pages/AdminProfilePage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
  {
    path: '/admin/tasks',
    name: 'admin.tasks',
    component: () => import('./pages/AdminTasksPage.vue'),
    meta: { layout: 'admin', requiresAdmin: true },
  },
]
